/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef client_CONSTANTS_H
#define client_CONSTANTS_H

#include "client_types.h"



class clientConstants {
 public:
  clientConstants();

};

extern const clientConstants g_client_constants;



#endif
